### ISSUE TITLE
Expose multiple rancher environments

### ISSUE THREAD

**Issue by jean-francois-labbe** [infinityworksltd/prometheus-rancher-exporter#10]
Hi,

I am using rancher and Prometheus and it's working great to see metrics from rancher environment where Prometheus is running.

I cannot see metrics from other rancher environments.

How can I add them to Prometheus monitoring?

**Comment by Rucknar** [comment]
Hey @jean-francois-labbe this can be done multiple ways. One way, is to run an exporter per environment you monitor, the results could then be separated by the static_configs labelling in Prometheus. The other way... You could potentially make use of a user based API key, instead of the current environment level API key. This should allow you to see everything your user can see.

I don't believe such a key could be automatically provisioned as we do so now, but i think you could create one and set it manually on the container using environment variables.

**Comment by jean-francois-labbe** [comment]
Thank you, I'll try this.
I just have to wait for rancher 1.2 support

**Comment by Rucknar** [comment]
@jean-francois-labbe 1.2 should be supported with the latest version (07) tag on github.
